### ISSUE TITLE
Problem with GraphQL

### ISSUE THREAD

**Issue by danieledifini** [postlight/headless-wp-starter#209] opened 2019-04-08 12:23 UTC
Hi there.
I have a problem with GraphQL, both frontend and backend.
http://localhost:3001/ gives me error "This site can't be reached".
http://localhost:8080/graphql gives me error "GraphQL Request must include at least one of those two parameters".
Any ideas?
Thanks in advance. Brilliant job!

**Comment by magidmroueh** [comment] 2019-09-19 11:02
http://localhost:3001/  error may caused by one of the following reasons:
1- the containers are not fully running, you need to wait for 3-4 minutes after the docker is done
2- you have an error while the containers are being built. we will need the logs in this case.

As for http://localhost:8080/graphql , this is the API URL to be used to call the apis, so you need to add parameters to know which end point to call.

closing this issue for now, please let me know if the above didn't help.

**Closed by magidmroueh** 2019-09-19 11:02 UTC
